# Generated by Django 6.0.5 on 2026-06-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200, null=True)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='images/Categories/')),
            ],
        ),
    ]
