# Generated by Django 6.0.5 on 2026-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_academicyear_options_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='សាលាបឋមសិក្សា', max_length=200)),
                ('school_name_en', models.CharField(blank=True, default='Primary School', max_length=200)),
                ('school_slogan', models.CharField(blank=True, default='Primary School MS', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school/favicon/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color e.g. #2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#4f46e5', help_text='Hex color e.g. #4f46e5', max_length=7)),
                ('sidebar_bg', models.CharField(default='#0b1120', help_text='Sidebar background color', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
