# Generated by Django 6.0.5 on 2026-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name (English)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name (English)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name (English)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name (English)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='នាមខ្លួន (ខ្មែរ)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='នាមត្រកូល (ខ្មែរ)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='នាមខ្លួន (ខ្មែរ)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='នាមត្រកូល (ខ្មែរ)'),
        ),
    ]
