# Generated by Django 6.0.5 on 2026-07-07 11:11

from django.db import migrations, models


def backfill_ids(apps, schema_editor):
    """Populate auto IDs for all existing records."""
    models_map = {
        'Classroom':    ('classroom_id',    'CLS'),
        'Subject':      ('subject_id',      'SUB'),
        'Exam':         ('exam_id',         'EXM'),
        'Notification': ('notification_id', 'NOT'),
        'ReportCard':   ('report_id',       'RPT'),
        'SchoolEvent':  ('event_id',        'EVT'),
    }
    for model_name, (field_name, prefix) in models_map.items():
        Model = apps.get_model('school', model_name)
        for obj in Model.objects.all():
            setattr(obj, field_name, f"{prefix}-{obj.pk:04d}")
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_first_name_en_student_last_name_en_and_more'),
    ]

    operations = [
        # Step 1: Add fields as nullable (so existing rows get NULL, no unique conflict)
        migrations.AddField(
            model_name='classroom',
            name='classroom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='report_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),

        # Step 2: Backfill IDs for existing rows
        migrations.RunPython(backfill_ids, migrations.RunPython.noop),
    ]
