# Generated by Django 6.0.5 on 2026-07-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_change_userprofile_student_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='វិញ្ញាបនប័ត្រ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contract_type',
            field=models.CharField(blank=True, help_text='អចិន្ត្រៃយ៍, កិច្ចសន្យា, ល្បែ', max_length=50, verbose_name='ប្រភេទកិច្ចសន្យា'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='សញ្ញាប័ត្រ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='អ្នកទំនាក់ទំនងបន្ទាន់'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ទូរស័ព្ទបន្ទាន់'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='ទំនាក់ទំនង'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ឆ្នាំបញ្ចប់ការសិក្សា'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ministry_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='លេខសម្គាល់ក្រសួង'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='អត្តសញ្ញាណប័ណ្ណ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, verbose_name='ទីកន្លែងកំណើត'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='ជួរប្រាក់ខែ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_license',
            field=models.CharField(blank=True, max_length=50, verbose_name='លេខអាជ្ញាប័ណ្ណគ្រូ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_rank',
            field=models.CharField(blank=True, choices=[('primary', 'គ្រូបឋមសិក្សា (Primary Teacher)'), ('secondary', 'គ្រូមធ្យមសិក្សា (Secondary Teacher)'), ('senior', 'គ្រូជាន់ខ្ពស់ (Senior Teacher)'), ('master', 'គ្រូបណ្ឌិត (Master Teacher)')], max_length=20, verbose_name='ជួរគ្រូ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_training',
            field=models.TextField(blank=True, verbose_name='បណ្តុះបណ្តាល'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(blank=True, max_length=200, verbose_name='សាកលវិទ្យាល័យ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_experience',
            field=models.IntegerField(default=0, verbose_name='ឆ្នាំបទពិសោធន៍'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចូលបម្រើការងារ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='កម្រិតវប្បធម៌'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='ជំនាញមុខវិជ្ជា'),
        ),
        migrations.CreateModel(
            name='TeacherEmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='ឈ្មោះសាលា')),
                ('position', models.CharField(max_length=100, verbose_name='តួនាទី')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់')),
                ('is_current', models.BooleanField(default=False, verbose_name='បច្ចុប្បន្ន')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ទីតាំង')),
                ('responsibilities', models.TextField(blank=True, verbose_name='ភារកិច្ច')),
                ('achievements', models.TextField(blank=True, verbose_name='សមិទ្ធផល')),
                ('reason_leaving', models.CharField(blank=True, max_length=200, verbose_name='មូលហេតុចាកចេញ')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='school.teacher', verbose_name='គ្រូ')),
            ],
            options={
                'verbose_name': 'ប្រវត្តិការងារ',
                'verbose_name_plural': 'ប្រវត្តិការងារ',
                'ordering': ['-start_date'],
            },
        ),
    ]
