# Generated by Django 6.0.5 on 2026-07-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_teacher_certifications_teacher_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/certificates/', verbose_name='ឯកសារវិញ្ញាបនប័ត្រ'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_card_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/id_cards/', verbose_name='ឯកសារអត្តសញ្ញាណប័ណ្ណ'),
        ),
    ]
