# Generated by Django 6.0.5 on 2026-07-28 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_teacher_certificate_file_teacher_id_card_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'អត្តសញ្ញាណប័ណ្ណ (ID Card)'), ('certificate', 'វិញ្ញាបនប័ត្រ (Certificate)'), ('degree', 'សញ្ញាប័ត្រសិក្សា (Degree)'), ('license', 'អាជ្ញាប័ណ្ណគ្រូ (Teacher License)'), ('contract', 'កិច្ចសន្យា (Contract)'), ('training', 'វិញ្ញាបនប័ត្របណ្តុះបណ្តាល (Training Certificate)'), ('other', 'ផ្សេងៗ (Other)')], max_length=20, verbose_name='ប្រភេទឯកសារ')),
                ('document_file', models.FileField(upload_to='documents/teachers/', verbose_name='ឯកសារ')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ចំណងជើង')),
                ('description', models.TextField(blank=True, verbose_name='ការពិពណ៌នា')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ថ្ងៃបញ្ចូល')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school.teacher')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='បញ្ចូលដោយ')),
            ],
            options={
                'verbose_name': 'ឯកសារគ្រូ',
                'verbose_name_plural': 'ឯកសារគ្រូ',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
