# Generated by Django 6.0.5 on 2026-08-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='ប្រតិកម្មحساសភាព'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/students/birth_certificates/', verbose_name='សំបុត្រកំណើត'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='លេខសំបុត្រកំណើត'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ឈ្មោះអ្នកទំនាក់ទំនងបន្ទាន់'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ទូរស័ព្ទបន្ទាន់'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='ទំនាក់ទំនង'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ឈ្មោះឪពុក'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='មុខរបរឪពុក'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ទូរស័ព្ទឪពុក'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/students/id_cards/', verbose_name='អត្តសញ្ញាណប័ណ្ណ/លិខិតឆ្លងដែន'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ឈ្មោះម្តាយ'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='មុខរបរម្តាយ'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ទូរស័ព្ទម្តាយ'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='ខ្មែរ', max_length=50, verbose_name='សញ្ជាតិ'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='មុខរបរឪពុកម្តាយ'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, verbose_name='ទីកន្លែងកំណើត'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='សាលារៀនមុន'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, verbose_name='សាសនា'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='អាសយដ្ឋាន'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, verbose_name='ក្រុមឈាម'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_date',
            field=models.DateField(auto_now_add=True, verbose_name='ថ្ងៃចុះឈ្មោះ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='សកម្ម'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True, verbose_name='កំណត់សម្គាល់សុខភាព'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='អ៊ីម៉ែលឪពុកម្តាយ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ឈ្មោះឪពុកម្តាយ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ទូរស័ព្ទឪពុកម្តាយ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ទូរស័ព្ទ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/Students/', verbose_name='រូបថត'),
        ),
    ]
