# Generated by Django 6.0.5 on 2026-08-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_student_allergies_student_birth_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់ការសិក្សា'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, help_text='ព័ត៌មានបន្ថែមអំពីសិស្ស', verbose_name='កំណត់ចំណាំ'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_classroom',
            field=models.CharField(blank=True, help_text='ថ្នាក់រៀនមុននេះ', max_length=200, verbose_name='ថ្នាក់មុន'),
        ),
        migrations.AddField(
            model_name='student',
            name='promotion_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃឡើងថ្នាក់'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'សកម្ម (Active)'), ('PROMOTED', 'ឡើងថ្នាក់ (Promoted)'), ('GRADUATED', 'បញ្ចប់ការសិក្សា (Graduated)'), ('TRANSFERRED', 'ផ្ទេរសាលា (Transferred)'), ('WITHDRAWN', 'ឈប់រៀន (Withdrawn)'), ('SUSPENDED', 'ផ្អាកការសិក្សា (Suspended)')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព'),
        ),
    ]
