# Generated by Django 6.0.5 on 2026-08-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_student_graduation_date_student_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(help_text='Stored for historical reference', max_length=100, verbose_name='ឈ្មោះថ្នាក់')),
                ('status', models.CharField(choices=[('ACTIVE', 'សកម្ម (Active)'), ('PROMOTED', 'ឡើងថ្នាក់ (Promoted)'), ('GRADUATED', 'បញ្ចប់ការសិក្សា (Graduated)'), ('TRANSFERRED', 'ផ្ទេរសាលា (Transferred)'), ('WITHDRAWN', 'ឈប់រៀន (Withdrawn)'), ('SUSPENDED', 'ផ្អាកការសិក្សា (Suspended)')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ពិន្ទុមធ្យម')),
                ('total_subjects', models.IntegerField(default=0, verbose_name='ចំនួនមុខវិជ្ជា')),
                ('passed_subjects', models.IntegerField(default=0, verbose_name='ជាប់មុខវិជ្ជា')),
                ('failed_subjects', models.IntegerField(default=0, verbose_name='ធ្លាក់មុខវិជ្ជា')),
                ('total_days', models.IntegerField(default=0, verbose_name='ថ្ងៃសរុប')),
                ('present_days', models.IntegerField(default=0, verbose_name='ថ្ងៃមកវត្តមាន')),
                ('absent_days', models.IntegerField(default=0, verbose_name='ថ្ងៃអវត្តមាន')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចាប់ផ្តើម')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបញ្ចប់')),
                ('notes', models.TextField(blank=True, verbose_name='កំណត់ចំណាំ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_histories', to='school.academicyear')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_histories', to='school.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='school.student')),
            ],
            options={
                'verbose_name': 'ប្រវត្តិសិស្ស',
                'verbose_name_plural': 'ប្រវត្តិសិស្ស',
                'ordering': ['-academic_year__year', 'student'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
