# Generated by Django 6.0.5 on 2026-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_studenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade_number', 'section']},
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_number',
            field=models.IntegerField(blank=True, help_text='1-12', null=True, verbose_name='លេខថ្នាក់'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.CharField(choices=[('primary', 'បឋមសិក្សា (Primary: Grade 1-6)'), ('lower_secondary', 'បឋមភូមិ (Lower Secondary: Grade 7-9)'), ('upper_secondary', 'មធ្យមភូមិ (Upper Secondary: Grade 10-12)')], default='primary', max_length=20, verbose_name='កម្រិតថ្នាក់'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='grade_level',
            field=models.CharField(blank=True, help_text='primary, lower_secondary, upper_secondary', max_length=20, verbose_name='កម្រិតថ្នាក់'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='grade_number',
            field=models.IntegerField(blank=True, help_text='1-12', null=True, verbose_name='លេខថ្នាក់'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='promoted_to',
            field=models.CharField(blank=True, help_text='Next grade/classroom after promotion', max_length=200, verbose_name='ឡើងថ្នាក់ទៅ'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='promotion_note',
            field=models.TextField(blank=True, verbose_name='កំណត់សំគាល់ការឡើងថ្នាក់'),
        ),
    ]
