# Generated by Django 6.0.5 on 2026-08-04 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_grade_options_grade_grade_number_grade_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', 'exam_time'], 'verbose_name': 'ប្រឡង', 'verbose_name_plural': 'ប្រឡង'},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={'ordering': ['name'], 'verbose_name': 'ប្រភេទប្រឡង', 'verbose_name_plural': 'ប្រភេទប្រឡង'},
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL, verbose_name='បង្កើតដោយ'),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(default=60, verbose_name='រយៈពេល (នាទី)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ម៉ោងប្រឡង'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='សេចក្តីណែនាំ'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='ពិន្ទុជាប់'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('scheduled', 'កំណត់ពេល (Scheduled)'), ('ongoing', 'កំពុងប្រឡង (Ongoing)'), ('completed', 'បានបញ្ចប់ (Completed)'), ('cancelled', 'បោះបង់ (Cancelled)')], default='scheduled', max_length=20, verbose_name='ស្ថានភាព'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='examtype',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='លេខកូដ'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ដំណើរការ'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='weight_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Weight in final grade calculation (e.g., Midterm=30%, Final=70%)', max_digits=5, verbose_name='ភាគរយទម្ងន់'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.academicyear', verbose_name='ឆ្នាំសិក្សា'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.classroom', verbose_name='ថ្នាក់'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='ថ្ងៃប្រឡង'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.examtype', verbose_name='ប្រភេទប្រឡង'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='ពិន្ទុអតិបរមា'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ឈ្មោះប្រឡង'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.subject', verbose_name='មុខវិជ្ជា'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះប្រភេទប្រឡង'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ពិន្ទុ')),
                ('grade_letter', models.CharField(blank=True, help_text='A, B, C, D, F', max_length=2, verbose_name='ពិន្ទុអក្សរ')),
                ('is_passed', models.BooleanField(default=False, verbose_name='ជាប់')),
                ('rank_in_class', models.IntegerField(blank=True, null=True, verbose_name='ចំណាត់ថ្នាក់')),
                ('was_present', models.BooleanField(default=True, verbose_name='មកប្រឡង')),
                ('absent_reason', models.CharField(blank=True, max_length=255, verbose_name='មូលហេតុអវត្តមាន')),
                ('remarks', models.TextField(blank=True, verbose_name='មតិយោបល់')),
                ('strengths', models.TextField(blank=True, verbose_name='ចំណុចខ្លាំង')),
                ('areas_to_improve', models.TextField(blank=True, verbose_name='ចំណុចត្រូវកែលម្អ')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ថ្ងៃបញ្ចូលពិន្ទុ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.exam', verbose_name='ប្រឡង')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results_recorded', to=settings.AUTH_USER_MODEL, verbose_name='បញ្ចូលដោយ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.student', verbose_name='សិស្ស')),
            ],
            options={
                'verbose_name': 'លទ្ធផលប្រឡង',
                'verbose_name_plural': 'លទ្ធផលប្រឡង',
                'ordering': ['-score'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
